---
- name: install node and npm
  hosts: 159.223.114.87
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Deploying nodejs app
  hosts: 159.223.114.87
  tasks:
    - name: Copy nodejs folder to a server
      copy:
        src: /root/nodejs-app/nodejs-app-1.0.0.tgz
        dest: /root/app-1.0.0.tgz
    - name: Unpack the nodejs file
      unarchive:
        src: /root/app-1.0.0.tgz
        dest: /root/
        remote_src: yes


# or 

---
- name: install node and npm
  hosts: 159.223.114.87
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Deploying nodejs app
  hosts: 159.223.114.87
  tasks:
    - name: Unpack the nodejs file
      unarchive:
        src: /root/nodejs-app/nodejs-app-1.0.0.tgz
        dest: /root/
        
# Project: Deploy NodeJS application - part 2
---
- name: install node and npm
  hosts: 159.223.114.87
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Deploying nodejs app
  hosts: 159.223.114.87
  tasks:
    - name: Unpack the nodejs file
      unarchive:
        src: /root/nodejs-app/nodejs-app-1.0.0.tgz
        dest: /root/
    - name: Install dependencies
      npm:
        path: /root/package
    - name: Start the application
      command:
        chdir: /root/package/app
        cmd: node server


# Project: Deploy NodeJS application - part 2 - to avoid that the play hangs 
---
- name: install node and npm
  hosts: 159.223.114.87
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Deploying nodejs app
  hosts: 159.223.114.87
  tasks:
    - name: Unpack the nodejs file
      unarchive:
        src: /root/nodejs-app/nodejs-app-1.0.0.tgz
        dest: /root/
    - name: Install dependencies
      npm:
        path: /root/package
    - name: Start the application
      command:
        chdir: /root/package/app
        cmd: node server
      async: 1000
      poll: 0

# Project: Deploy NodeJS application - part 2 - Ensure app is running
---
- name: install node and npm
  hosts: 159.223.114.87
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Deploying nodejs app
  hosts: 159.223.114.87
  tasks:
    - name: Unpack the nodejs file
      unarchive:
        src: /root/nodejs-app/nodejs-app-1.0.0.tgz
        dest: /root/
    - name: Install dependencies
      npm:
        path: /root/package
    - name: Start the application
      command:
        chdir: /root/package/app
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}